language: php
sudo: true

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 7.2
          env: SYMFONY_VERSION=4.4.*
        - php: 7.3
          env: SYMFONY_VERSION=4.4.*
        - php: 7.4
          env: SYMFONY_VERSION=4.4.*
        - php: 7.2
          env: SYMFONY_VERSION=5.0.*
        - php: 7.3
          env: SYMFONY_VERSION=5.0.*
        - php: 7.4
          env: SYMFONY_VERSION=5.0.*
        - php: 8.2
          env: SYMFONY_VERSION=5.0.*
        - php: 8.2
          env: SYMFONY_VERSION=6.0.*
    fast_finish: true

before_script:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - composer install

script:
    - mkdir -p tests/coverage
    - php vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls -v

before_install: 
    - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
