language: php
sudo: true

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 5.3
          env: SYMFONY_VERSION=2.7.*
        - php: 5.4
          env: SYMFONY_VERSION=2.8.*
        - php: 5.5
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 7.0
          env: SYMFONY_VERSION=2.8.*
        - php: 7.0
          env: SYMFONY_VERSION=3.0.*
        - php: 7.0
          env: SYMFONY_VERSION=3.1.*
        - php: 7.0
          env: SYMFONY_VERSION=3.2.*
        - php: 7.0
          env: SYMFONY_VERSION=3.3.*
        - php: 7.1
          env: SYMFONY_VERSION=3.3.*
    fast_finish: true

before_script:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - composer install

script:
    - mkdir -p Tests/coverage
    - vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls -v

before_install: 
    - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
