name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.4]
        symfony-version: ['~5.4', '~6.4', '~7.4']
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          extensions: xdebug
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: $HOME/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          rm -rf vendor composer.lock
          composer require "symfony/symfony:${{ matrix.symfony-version }}" --no-update
          COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-progress

      - name: Setup Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov

      - name: Run PHP CS Fixer
        env:
          PHP_CS_FIXER_TARGET_BRANCH: master
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose --using-cache=no

      - name: Run Rector
        run: vendor/bin/rector process --dry-run --no-progress-bar --ansi

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze --no-progress --ansi

      - name: Run PHPUnit tests
        run: XDEBUG_MODE=coverage php vendor/bin/phpunit

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          ./codecov -r BowlOfSoup/NormalizerBundle -B "${BRANCH}"